import './globals.css'
import { Inter } from 'next/font/google'
import DropdownNavbar from "./components/NavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Menstagram',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DropdownNavbar />
        {children}
      </body>
    </html>
  )
}
